<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-PCCUKN8F" failures="1" tests="1" name="Default test" time="5.523" errors="0" timestamp="2023-06-13T19:35:01 CDT">
  <testcase classname="com.automation.tests.AutomationScripts" name="login_Success_2" time="2.572">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;com.automation.utility.ExtentReportsUtility.testLogger&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "com.automation.utility.ExtentReportsUtility.testLogger" is null
at com.automation.utility.ExtentReportsUtility.logTestInfo(ExtentReportsUtility.java:50)
at com.automation.base.BaseTest.clickOnElement(BaseTest.java:114)
at com.automation.tests.AutomationScripts.login_Success_2(AutomationScripts.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login_Success_2 -->
  <testcase classname="com.automation.tests.AutomationScripts" name="Forgot_Password_04A" time="0.0">
    <ignored/>
  </testcase> <!-- Forgot_Password_04A -->
  <testcase classname="com.automation.tests.AutomationScripts" name="Forgot_Password_04B" time="0.0">
    <ignored/>
  </testcase> <!-- Forgot_Password_04B -->
  <testcase classname="com.automation.tests.AutomationScripts" name="login_Error_Message_1" time="0.0">
    <ignored/>
  </testcase> <!-- login_Error_Message_1 -->
  <testcase classname="com.automation.tests.AutomationScripts" name="check_Remember_Me_03" time="0.0">
    <ignored/>
  </testcase> <!-- check_Remember_Me_03 -->
  <testcase classname="com.automation.tests.AutomationScripts" name="user_Menu_dropdown_05" time="0.0">
    <ignored/>
  </testcase> <!-- user_Menu_dropdown_05 -->
</testsuite> <!-- Default test -->
